const API={products:'/.netlify/functions/products',upload:'/.netlify/functions/upload'};
const CATEGORIES=[{name:'Ilovalar',icon:'◫',desc:'Android va boshqa platformalar uchun ilovalar.'},{name:'Saytlar',icon:'◎',desc:'Foydali va qiziqarli saytlar.'},{name:'Kitoblar',icon:'▣',desc:'Elektron kitoblar kutubxonasi.'},{name:'Jurnallar',icon:'▤',desc:'Jurnallar va nashrlar.'}];
let state={products:[],query:''};
const $=(s,r=document)=>r.querySelector(s);const h=t=>String(t??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const adminPassword=()=>localStorage.getItem('hmarket_admin_password')||'';const isAdminPath=()=>location.pathname.replace(/\/$/,'')==='/admin';const productSlug=()=>{let m=location.pathname.match(/^\/product\/([^/]+)/);return m?decodeURIComponent(m[1]):null};
function toast(m){let t=document.createElement('div');t.className='toast';t.textContent=m;document.body.appendChild(t);setTimeout(()=>t.remove(),3500)}
function cat(){return new URL(location.href).searchParams.get('cat')||'Hammasi'}
async function fetchProducts(){try{let r=await fetch(API.products);let txt=await r.text();let d=txt?JSON.parse(txt):null;if(!r.ok||!d?.ok)throw Error(d?.message||'xato');state.products=d.products||[]}catch(e){console.error(e);state.products=[];if(!isAdminPath())toast('Mahsulotlar yuklanmadi')}}
function brand(){return `<span class="brand"><img src="/assets/logo.svg" alt="H Market"><span class="brandText"><b>H</b> MARKET</span></span>`}
function shell(content){return `<div class="navShell wrap"><header class="nav"><a href="/">${brand()}</a><nav class="links"><a href="/" class="${cat()==='Hammasi'&&!productSlug()?'active':''}">Bosh sahifa</a>${CATEGORIES.map(c=>`<a class="${cat()===c.name?'active':''}" href="/?cat=${encodeURIComponent(c.name)}">${c.name}</a>`).join('')}<a href="#footer">Aloqa</a></nav><button class="iconBtn">☾</button></header></div>${content}<footer class="footer" id="footer"><div class="wrap footerGrid"><div>${brand()}<p>Ilovalar, saytlar, kitoblar va jurnallar — hammasi bir joyda.</p></div><div><h4>Platforma</h4><ul>${CATEGORIES.map(c=>`<li><a href="/?cat=${encodeURIComponent(c.name)}">${c.name}</a></li>`).join('')}</ul></div><div><h4>Ma’lumot</h4><p>Biz haqimizda<br>Qoidalar<br>Maxfiylik siyosati</p></div><div><h4>Aloqa</h4><p>info@hmarket.uz<br>www.hmarket.uz</p></div></div><div class="wrap bottomLine"><div>© 2026 H Market.</div><div>Maxfiylik • Shartlar</div></div></footer>`}
function productCard(p){let img=p.imageUrl||'/assets/logo.svg';return `<a class="card productCard" href="/product/${encodeURIComponent(p.slug||p.id)}"><div class="productThumb ${img.includes('logo')?'logo':''}"><img src="${h(img)}" onerror="this.src='/assets/logo.svg'"></div><div class="productBody"><div class="badgeRow"><span class="badge">${h(p.category)}</span><span class="rating">★ ${h(p.rating||'4.8')}</span></div><h3>${h(p.title)}</h3><p>${h((p.description||'').slice(0,92))}${(p.description||'').length>92?'...':''}</p><div class="go"><span>Batafsil</span><span>→</span></div></div></a>`}
function filtered(){let c=cat(),q=state.query.trim().toLowerCase();return state.products.filter(p=>(c==='Hammasi'||p.category===c)&&(!q||[p.title,p.category,p.description,p.fileName].join(' ').toLowerCase().includes(q)))}
function renderHome(){let products=filtered();$('#app').innerHTML=shell(`<main class="wrap"><section class="hero"><div><h1>H Market — hammasi bir joyda</h1><p>Ilovalar, saytlar, kitoblar va jurnallarni bir platformada toping. Sifatli va ishonchli kontentlar siz uchun.</p><div class="searchBar"><span>⌕</span><input id="searchInput" placeholder="Qidirish..." value="${h(state.query)}"><button>⌕</button></div><div class="heroBtns"><a class="ctaBtn" href="#products">Ko‘rish →</a><a class="ghostBtn" href="/?cat=Ilovalar">Boshlash</a></div></div><div class="heroStage"><div class="floatChip c1">◫</div><div class="floatChip c2">◎</div><div class="floatChip c3">▤</div><div class="floatChip c4">▣</div><img class="bigLogo" src="/assets/logo.svg"><div class="pedestal"></div></div></section><section class="gridFour">${CATEGORIES.map(c=>`<a class="card catCard" href="/?cat=${encodeURIComponent(c.name)}"><div class="catIcon">${c.icon}</div><div><h3>${c.name}</h3><p>${c.desc}</p><b>Ko‘rish →</b></div></a>`).join('')}</section><section id="products"><div class="sectionHead"><h2>${cat()==='Hammasi'?'Tavsiya etilgan':h(cat())}</h2><a href="/">Hammasini ko‘rish →</a></div><div class="products">${products.length?products.map(productCard).join(''):'<div class="card emptyState" style="grid-column:1/-1">Mahsulot topilmadi.</div>'}</div></section></main>`);$('#searchInput').addEventListener('input',e=>{state.query=e.target.value;renderHome()})}
function renderProduct(){let p=state.products.find(x=>(x.slug||x.id)===productSlug());if(!p){$('#app').innerHTML=shell('<main class="wrap"><div class="card emptyState">Mahsulot topilmadi.</div></main>');return}$('#app').innerHTML=shell(`<main class="wrap productPage"><div class="card productImage"><img src="${h(p.imageUrl||'/assets/logo.svg')}" onerror="this.src='/assets/logo.svg'"></div><div class="card productInfo"><span class="badge">${h(p.category)}</span><h1>${h(p.title)}</h1><p>${h(p.description||'')}</p><p><b>Fayl:</b> ${h(p.fileName||'Yuklab olish')}</p><p><b>Reyting:</b> ★ ${h(p.rating||'4.8')}</p><div class="heroBtns"><a class="ctaBtn" href="${h(p.fileUrl)}" target="_blank">Yuklab olish ↓</a><a class="ghostBtn" href="/">Orqaga</a></div></div></main>`)}
function adminShell(content){return `<div class="wrap"><div class="adminHeader"><a class="minBrand" href="/"><img src="/assets/logo.svg">H Market</a><a class="smallBtn" href="/">Bosh sahifa</a></div></div>${content}`}
function renderLogin(){document.title='Admin panel — H Market';$('#app').innerHTML=adminShell(`<main class="authWrap wrap"><form class="card authCard" id="loginForm"><h1>Admin panel</h1><p class="muted">Bu sahifa faqat /admin orqali ochiladi.</p><div class="field"><label>Parol</label><input type="password" id="pass" placeholder="Admin parol"></div><button class="ctaBtn" style="width:100%">Kirish</button><div class="hint">Standart parol: admin123</div></form></main>`);$('#loginForm').onsubmit=e=>{e.preventDefault();localStorage.setItem('hmarket_admin_password',$('#pass').value.trim());renderAdmin()}}
async function readJsonResponse(res,name){let text=await res.text(),data;try{data=text?JSON.parse(text):null}catch{throw Error(`${name}: server JSON qaytarmadi (${res.status})`)}if(!res.ok||!data?.ok)throw Error(data?.message||`${name} xatosi`);return data}
async function uploadFile(file){if(!file)throw Error('Fayl tanlanmagan');if(file.size>4*1024*1024)throw Error(`Fayl ${(file.size/1024/1024).toFixed(1)} MB. Limit 4 MB.`);let res=await fetch(API.upload,{method:'POST',headers:{'content-type':file.type||'application/octet-stream','x-admin-password':adminPassword(),'x-file-name':encodeURIComponent(file.name)},body:file});return readJsonResponse(res,'Fayl yuklash')}
async function saveProduct(payload){let res=await fetch(API.products,{method:'POST',headers:{'content-type':'application/json','x-admin-password':adminPassword()},body:JSON.stringify(payload)});return readJsonResponse(res,'Saqlash')}
async function removeProduct(id){if(!confirm('O‘chirilsinmi?'))return;try{let res=await fetch(API.products,{method:'DELETE',headers:{'content-type':'application/json','x-admin-password':adminPassword()},body:JSON.stringify({id})});await readJsonResponse(res,'O‘chirish');await fetchProducts();renderAdminPanel();toast('O‘chirildi')}catch(e){toast(e.message)}}window.removeProduct=removeProduct;
function renderAdminPanel(){$('#app').innerHTML=adminShell(`<main class="wrap adminWrap"><div class="adminTop"><h1>Admin panel</h1><div><button class="smallBtn" id="logoutBtn">Chiqish</button> <a class="smallBtn" href="/" target="_blank">Saytni ko‘rish</a></div></div><div class="adminGrid"><section class="card formCard"><h2>Yangi mahsulot</h2><form id="productForm"><div class="field"><label>Nomi</label><input id="title" required></div><div class="field"><label>Kategoriya</label><select id="category">${CATEGORIES.map(c=>`<option>${c.name}</option>`).join('')}</select></div><div class="field"><label>Reyting</label><input id="rating" value="4.8"></div><div class="field"><label>Tavsif</label><textarea id="description"></textarea></div><div class="field"><label>Rasm / muqova</label><input id="imageFile" type="file" accept="image/*"><div class="previewBox" id="imagePreview">Preview</div></div><div class="field"><label>Yuklab olinadigan fayl</label><input id="mainFile" type="file" required><div class="hint">APK, PDF, ZIP. Limit 4 MB.</div></div><button class="ctaBtn" id="saveBtn" style="width:100%">Fayl yuklash va saqlash</button></form></section><section class="card tableCard"><h2>Mahsulotlar</h2><div class="tableWrap"><table class="table"><thead><tr><th>Nomi</th><th>Kategoriya</th><th>Link</th><th>Amal</th></tr></thead><tbody>${state.products.map(p=>`<tr><td><b>${h(p.title)}</b><br><span class="muted">${h(p.fileName||'')}</span></td><td>${h(p.category)}</td><td><a href="/product/${encodeURIComponent(p.slug||p.id)}" target="_blank">Ochish</a></td><td><button class="smallBtn dangerBtn" onclick="removeProduct('${h(p.id)}')">O‘chirish</button></td></tr>`).join('')||'<tr><td colspan="4">Mahsulot yo‘q</td></tr>'}</tbody></table></div></section></div></main>`);$('#logoutBtn').onclick=()=>{localStorage.removeItem('hmarket_admin_password');renderLogin()};$('#imageFile').onchange=()=>{let f=$('#imageFile').files[0];$('#imagePreview').innerHTML=f?`<img src="${URL.createObjectURL(f)}">`:'Preview'};$('#productForm').onsubmit=async e=>{e.preventDefault();let b=$('#saveBtn');b.disabled=true;b.textContent='Yuklanmoqda...';try{let up=await uploadFile($('#mainFile').files[0]);let imageUrl='/assets/logo.svg';if($('#imageFile').files[0])imageUrl=(await uploadFile($('#imageFile').files[0])).fileUrl;await saveProduct({title:$('#title').value,category:$('#category').value,description:$('#description').value,rating:$('#rating').value,imageUrl,fileUrl:up.fileUrl,fileName:up.fileName,fileType:up.contentType});await fetchProducts();renderAdminPanel();toast('Saqlandi')}catch(e){toast(e.message)}finally{b.disabled=false;b.textContent='Fayl yuklash va saqlash'}}}
async function renderAdmin(){if(!adminPassword())return renderLogin();await fetchProducts();renderAdminPanel()}
async function init(){if(isAdminPath())return renderAdmin();await fetchProducts();if(productSlug())return renderProduct();renderHome()}init();